// <auto-generated />
namespace KandM_Clothes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixBugCantFindImg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixBugCantFindImg));
        
        string IMigrationMetadata.Id
        {
            get { return "202405211623355_FixBugCantFindImg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
